#ifndef _EZIV_LOG_INCLUDE_
#define _EZIV_LOG_INCLUDE_

#include "osp.h"

enum EM_EZIV_LOGMODULE
{
	EM_EZIV_LOGMODULE_SYS = 0,
	EM_EZIV_LOGMODULE_VIDEO_INPUT,
	EM_EZIV_LOGMODULE_PROCESS,
	EM_EZIV_LOGMODULE_RESULT,
	EM_EZIV_LOGMODULE_ALARM,
	EM_EZIV_LOGMODULE_VIDEO_CONNECT,
	EM_EZIV_LOGMODULE_VIDEO_DISPATCH,
	EM_EZIV_LOGMODULE_RECORD,
	EM_EZIV_LOGMODULE_DB,
};

enum EM_EZIV_LOGLEVEL
{
	EM_LOGLEVEL_FATEL = 0,
	EM_LOGLEVEL_EXP,
	EM_LOGLEVEL_ERROR,
	EM_LOGLEVEL_WARNING,
	EM_LOGLEVEL_IMPT,
	EM_LOGLEVEL_INFO,
	EM_LOGLEVEL_DEBUG,
};

enum EM_EZIV_LOGTYPE
{
	EM_EZIV_LOGTYPE_SYS = 0,
	EM_EZIV_LOGTYPE_DB,
	EM_EZIV_LOGTYPE_VIDEO,
	EM_EZIV_LOGTYPE_CV,
	EM_EZIV_LOGTYPE_ALARM,
	EM_EZIV_LOGTYPE_CLIENT,
};

/*
enum EZIV_MODULE
{
	EZIV_SERVER,
	EZIV_DB,
	EZIV_VIDEO,
	EZIV_CV,
	EZIV_ALARM,
	EZIV_CLIENT,
};
*/

#ifndef LOG_BUFFER_SIZE
#define LOG_BUFFER_SIZE				1024*8
#endif

API void IVLog(EM_EZIV_LOGMODULE emModule, EM_EZIV_LOGLEVEL emLevel, EM_EZIV_LOGTYPE emMsgType, const s8* pchFormat, ... );

#endif //_EZIV_LOG_INCLUDE_
